package cwssql

import (
	"time"

	"gorm.io/datatypes"
)

// LegacyBaseIdModel provides a base model with UUID primary key using uuid_generate_v4() function
// This is for legacy PostgreSQL versions that don't support gen_random_uuid()
type LegacyBaseIdModel struct {
	// Id is the primary key field with UUID generated by uuid_generate_v4()
	Id string `gorm:"type:text;primaryKey;default:uuid_generate_v4()" json:"id"`
}

// BaseIdModel provides a base model with UUID primary key using gen_random_uuid() function
// This is for modern PostgreSQL versions (13+)
type BaseIdModel struct {
	// Id is the primary key field with UUID generated by gen_random_uuid()
	Id string `gorm:"type:text;primaryKey;default:gen_random_uuid()" json:"id"`
}

// BaseTimeModel provides automatic timestamp fields for created and updated times
type BaseTimeModel struct {
	// CreatedAt is automatically set when the record is created
	CreatedAt time.Time `gorm:"autoCreateTime" json:"created_at"`
	// UpdatedAt is automatically updated when the record is modified
	UpdatedAt time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}

// BaseJsonBModel provides a base model with a JSONB field for PostgreSQL
type BaseJsonModel struct {
	// JsonBData stores arbitrary JSON data in PostgreSQL JSONB format
	JsonData datatypes.JSON `gorm:"type:json" json:"json_data"`
}
